<?php
namespace Database\Seeders;

use App\Models\front\plans;
use App\Models\Option;
use App\Models\Providers;
use Illuminate\Database\Seeder;

class OptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'key' => 'site_name',
                'value' => 'sms',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Site Name',
                'sort' => 1,
                'group' => 0,

            ],
            [
                'key' => 'site_logo',
                'value' => 'options/site_logo.png',
                'label' => 'Site Logo',
                'is_image' => true,
                'is_boolean' => false,
                'sort' => 1,
                'group' => 0,
            ],
            [
                'key' => 'dark_site_logo',
                'value' => 'options/site_logo.png',
                'is_image' => true,
                'is_boolean' => false,
                'label' => 'Site Logo (Dark)',
                'sort' => 1,
                'group' => 0,
            ],
            [
                'key' => 'site_description',
                'value' => 'Reviews,Likes,Comments,Shares,Follows',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Site Description',
                'sort' => 2,
                'group' => 0,
            ],
            [
                'key' => 'website_keywords',
                'value' => 'Reviews,Likes,Comments,Shares,Follows',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Site Keywords',
                'sort' => 3,
                'group' => 0,
            ],
            [
                'key' => 'default_plan',
                'value' => '1',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Default  plan',
                'sort' => 2,
                'group' => 1,
            ],
            [
                'key' => 'facebook',
                'value' => 'https://www.facebook.com/',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Facebook',
                'sort' => 1,
                'group' => 3,
            ],
            [
                'key' => 'twitter',
                'value' => 'https://www.twitter.com/',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Twitter',
                'sort' => 2,
                'group' => 3,
            ],
            [
                'key' => 'youtube',
                'value' => 'https://www.youtube.com/',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Youtube',
                'sort' => 3,
                'group' => 3,
            ],
            [
                'key' => 'whatsapp',
                'value' => 'https://www.watsapp.com/',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Whatsapp',
                'sort' => 4,
                'group' => 3,
            ],
            [
                'key' => 'email_from',
                'value' => 'example@gmail.com',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Email from',
                'sort' => 0,
                'group' => 4,
            ],
            [
                'key' => 'email_name',
                'value' => 'Review',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Your name',
                'sort' => 1,
                'group' => 4,
            ],
            [
                'key' => 'email_protocal',
                'value' => '0',
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'Email Protocol',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'email_smtp_server',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'SMTP Server',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'email_smtp_port',
                'value' => null,
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'SMTP Port',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'email_smtp_encryption',
                'value' => '0',
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'SMTP Encryption',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'email_smtp_username',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'SMTP Username',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'email_smtp_password',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'SMTP Password',
                'sort' => 2,
                'group' => 4,
            ],
            [
                'key' => 'facebook_login_status',
                'value' => '0',
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'Facebook status',
                'sort' => 0,
                'group' => 5,
            ],
            [
                'key' => 'facebook_login_app_id',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Facebook app id',
                'sort' => 1,
                'group' => 5,
            ],
            [
                'key' => 'facebook_login_app_secret',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Facebook app secret',
                'sort' => 2,
                'group' => 5,
            ],
            [
                'key' => 'google_login_status',
                'value' => '0',
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'Google status',
                'sort' => 3,
                'group' => 5,
            ],
            [
                'key' => 'google_login_client_id',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Google client id',
                'sort' => 4,
                'group' => 5,
            ],
            [
                'key' => 'google_login_client_secret',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Google client secret',
                'sort' => 5,
                'group' => 5,
            ],
            [
                'key' => 'twitter_login_status',
                'value' => '0',
                'is_image' => false,
                'is_boolean' => 1,
                'label' => 'Twitter status',
                'sort' => 6,
                'group' => 5,
            ],
            [
                'key' => 'twitter_login_consumer_key',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Twitter consumer key',
                'sort' => 7,
                'group' => 5,
            ],
            [
                'key' => 'twitter_login_consumer_secret',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Twitter consumer secret',
                'sort' => 8,
                'group' => 5,
            ],
            [
                'key' => 'recaptcha_status',
                'value' => 1,
                'is_image' => false,
                'is_boolean' => 0,
                'label' => 'reCaptcha status',
                'sort' => 0,
                'group' => 6,
            ],
            [
                'key' => 'google_site_key',
                'value' => '6LeIZ74hAAAAAH1w2GWQuNsd2X5JuWmPRdkPS4ai',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Google site key',
                'sort' => 1,
                'group' => 6,
            ],
            [
                'key' => 'google_secret_key',
                'value' => '6LeIZ74hAAAAAJ2oexzVyqt2ZPcsyZz1DXqCRRwA',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Google secret key',
                'sort' => 2,
                'group' => 6,
            ],
            [
                'key' => 'instance_id',
                'value' => '65560E4DDD7BA',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Instance ID',
                'sort' => 1,
                'group' => 7,
            ],
            [
                'key' => 'access_token',
                'value' => '6492ab7ba07f8',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Access Token',
                'sort' => 2,
                'group' => 7,
            ],
            [
                'key' => 'default_store',
                'value' => '1',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Default Store',
                'sort' => 0,
                'group' => 8,
            ],
            [
                'key' => 'usdt_rate',
                'value' => '1',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'USDT Rate',
                'sort' => 0,
                'group' => 9,
            ],
            [
                'key' => 'usd_rate',
                'value' => '1',
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'USD Rate',
                'sort' => 1,
                'group' => 9,
            ],
            [
                'key' => 'embed_code',
                'value' => null,
                'is_image' => false,
                'is_boolean' => false,
                'label' => 'Embed code',
                'sort' => 0,
                'group' => 10,
            ],

        ];

        foreach ($data as $item) {
            Option::create($item);
        }

        $data1 = [
            [
                'name' => 'Plan A',
                'min' => 1,
                'max' => 100,
                'cost' => 4.99,
                'status' => 1,
            ],
            [
                'name' => 'Plan B',
                'min' => 101,
                'max' => 1000,
                'cost' => 24.99,
                'status' => 1,
            ], [
                'name' => 'Plan C',
                'min' => 1001,
                'max' => 2000,
                'cost' => 34.99,
                'status' => 1,
            ], [
                'name' => 'Plan D',
                'min' => 2001,
                'max' => 5000,
                'cost' => 44.99,
                'status' => 1,
            ],
        ];

        foreach ($data1 as $item) {
            plans::create($item);
        }
        $data2 = [
            [
                'name' => 'VF-Cash',
                'icon' => null,
                'start_body' => 'تم استلام',
                'msg_body' => 'تم استلام مبلغ 87.00 جنيه من رقم 01124045720؛ المسجل بإسم Moemen T Moustafa تاريخ العملية 30-12-22 08:58 رقم العملية 002712980149.',
                'amount' => 'مبلغ',
                'phone' => 'رقم',
                'transaction_no' => 'رقم العملية',
                'status' => 1,
            ],
            [
                'name' => 'ET Cash',
                'icon' => null,
                'start_body' => 'تم استلام',
                'msg_body' => 'تم إستلام مبلغ 26.00 ج.م من رقم 01029049629 المسجل باسمMohamed S Hamed   بنجاح. رصيد محفظتك الحالى 298.21 ج.م. لتقييم خدمات محفظة اتصالات كاش إطلب #14*777*',
                'amount' => 'مبلغ',
                'phone' => 'من رقم',
                'transaction_no' => null,
                'status' => 1,
            ],
            [
                'name' => 'OrangeCash',
                'icon' => null,
                'start_body' => 'تم استلام',
                'msg_body' => 'تم إستلام عملية تحويل أموال بمبلغ 500.00 جنيه من Mohamed A Eid، رصيدك الحالي 582.75 جنية. رقم المعاملة 1854773116',
                'amount' => 'مبلغ',
                'phone' => null,
                'transaction_no' => 'رقم المعاملة',
                'status' => 1,
            ],
            [
                'name' => 'We-Pay',
                'icon' => null,
                'start_body' => 'تم استلام',
                'msg_body' => 'VF-Cash',
                'amount' => '3',
                'phone' => '7',
                'transaction_no' => '20',
                'status' => 1,
            ]
            ,
            [
                'name' => 'BanK-AlAhly',
                'icon' => null,
                'start_body' => 'تم إضافة تحويل لحظي لحسابكم',
                'msg_body' => 'تم إضافة تحويل لحظي لحسابكم رقم 0180 بمبلغ 700 جم من MOHAMED AHMED ABDELATY AHMED EID رقم مرجعي 300501086322 يوم 01-05 الساعة 21:36 للمزيد اتصل بـ 19623',
                'amount' => 'بمبلغ',
                'phone' => null,
                'transaction_no' => 'رقم مرجعي',
                'status' => 1,
            ],
            [
                'name' => 'ALEXBANK',
                'icon' => null,
                'start_body' => 'لقد استقبلت تحويل من خلال تطبيق',
                'msg_body' => 'لقد استقبلت تحويل من خلال تطبيق Instapay على **9001 بقيمة 700.00 جم من عزه عبدالستار ابراهيم ابراهيم. رقم المعاملة هو ac58cf69',
                'amount' => 'بقيمة',
                'phone' => null,
                'transaction_no' => 'رقم المعاملة',
                'status' => 1,
            ],
        ];

        foreach ($data2 as $item) {
            Providers::create($item);
        }

    }
}
